language: node_js

node_js:
    - "0.12"
    - "0.11"
    - "0.10"

before_script:
    # Open the browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    # install dependencies
    - npm install -g gulp bower
    - npm install
    - bower install

script: gulp && gulp ci
